import fs from "node:fs";
import path from "node:path";
import Papa from "papaparse";
import { batchSortKey, UNPARSEABLE_BATCH } from "@/lib/batch-sort";
export { batchSortKey };

// The Python pipeline writes its output to ../data relative to this app
// (yc_mind/data/), regenerated by scripts/scrape_companies.py + build_trends.py.
// Reading from disk on every request (no caching) means re-running those
// scripts updates the dashboard without rebuilding this app.
const DATA_DIR = path.join(process.cwd(), "..", "data");

function readCsv(filename: string): Record<string, string>[] {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, "utf-8");
  const { data } = Papa.parse<Record<string, string>>(content, {
    header: true,
    skipEmptyLines: true,
  });
  return data;
}

export type Company = {
  name: string;
  slug: string;
  batch: string;
  status: string;
  industry: string;
  subindustry: string;
  one_liner: string;
  team_size: number | null;
  all_locations: string;
  website: string;
  stage: string;
  launched_at: number | null;
  top_company: boolean;
  tags: string[];
  industries: string[];
  regions: string[];
};

export function getCompanies(): Company[] {
  return readCsv("companies.csv").map((row) => ({
    name: row.name ?? "",
    slug: row.slug ?? "",
    batch: row.batch ?? "",
    status: row.status ?? "",
    industry: row.industry ?? "",
    subindustry: row.subindustry ?? "",
    one_liner: row.one_liner ?? "",
    team_size: row.team_size ? Number(row.team_size) : null,
    all_locations: row.all_locations ?? "",
    website: row.website ?? "",
    stage: row.stage ?? "",
    launched_at: row.launched_at ? Number(row.launched_at) : null,
    top_company: row.top_company === "True" || row.top_company === "true",
    tags: row.tags ? row.tags.split("|").filter(Boolean) : [],
    industries: row.industries ? row.industries.split("|").filter(Boolean) : [],
    regions: row.regions ? row.regions.split("|").filter(Boolean) : [],
  }));
}

export type ShareTable = {
  batches: string[];
  categories: string[];
  // share[batch][category] = 0..1
  share: Record<string, Record<string, number>>;
};

import { type TrendField } from "@/lib/trend-fields";
export type { TrendField };

export function getShareTable(field: TrendField): ShareTable {
  const rows = readCsv(`trend_share_${field}.csv`);
  const batches: string[] = [];
  const categorySet = new Set<string>();
  const share: Record<string, Record<string, number>> = {};

  for (const row of rows) {
    const batch = row[""];
    if (!batch) continue;
    batches.push(batch);
    share[batch] = {};
    for (const [key, val] of Object.entries(row)) {
      if (key === "") continue;
      categorySet.add(key);
      share[batch][key] = Number(val) || 0;
    }
  }

  return { batches, categories: Array.from(categorySet), share };
}

export type Mover = {
  theme: string;
  baselineShare: number;
  recentShare: number;
  change: number;
};

export function getMovers(field: TrendField): Mover[] {
  const rows = readCsv(`trend_movers_${field}.csv`);
  return rows
    .map((row) => ({
      theme: row[""] ?? "",
      baselineShare: Number(row.baseline_share) || 0,
      recentShare: Number(row.recent_share) || 0,
      change: Number(row.change) || 0,
    }))
    .filter((m) => m.theme);
}

export type BatchSize = { batch: string; count: number };

/**
 * `realOnly` drops "Unspecified" / unparseable batch labels (matches the
 * Python pipeline's `_is_real_batch`). `minSize` additionally drops sparse
 * announced-but-unfilled future batches — pass 30 to mirror the trend
 * analysis's `--min-size` default.
 */
export function getBatchSizes({
  realOnly = true,
  minSize = 0,
}: { realOnly?: boolean; minSize?: number } = {}): BatchSize[] {
  const companies = getCompanies();
  const counts = new Map<string, number>();
  for (const c of companies) {
    if (!c.batch) continue;
    if (realOnly && batchSortKey(c.batch) === UNPARSEABLE_BATCH) continue;
    counts.set(c.batch, (counts.get(c.batch) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([batch, count]) => ({ batch, count }))
    .filter((b) => b.count >= minSize)
    .sort((a, b) => batchSortKey(a.batch) - batchSortKey(b.batch));
}

export function getIdeasMarkdown(): string {
  const filePath = path.join(DATA_DIR, "ideas.md");
  if (!fs.existsSync(filePath)) return "";
  return fs.readFileSync(filePath, "utf-8");
}

export function getDataFreshness(): { companiesUpdatedAt: string | null; totalCompanies: number } {
  const filePath = path.join(DATA_DIR, "companies.jsonl");
  if (!fs.existsSync(filePath)) return { companiesUpdatedAt: null, totalCompanies: 0 };
  const stat = fs.statSync(filePath);
  const totalCompanies = getCompanies().length;
  return { companiesUpdatedAt: stat.mtime.toISOString(), totalCompanies };
}
