import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { getIdeasMarkdown } from "@/lib/data";

export const dynamic = "force-dynamic";

export default function IdeasPage() {
  const markdown = getIdeasMarkdown();

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">
          Stage 2
        </p>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
          Generated startup ideas
        </h1>
        <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
          Generated by a Claude session reading the grounded trend context (no API
          key — see <code className="rounded bg-secondary px-1.5 py-0.5">data/idea_prompt.md</code>{" "}
          for the source prompt).
        </p>
      </div>

      <div className="rounded-[1.75rem] border border-border/80 bg-card p-6 shadow-sm sm:p-8">
        {markdown ? (
          <article className="prose-yc">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
          </article>
        ) : (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No ideas generated yet — run{" "}
            <code className="rounded bg-secondary px-1.5 py-0.5">
              build_idea_context.py
            </code>{" "}
            and have a Claude session write <code className="rounded bg-secondary px-1.5 py-0.5">data/ideas.md</code>.
          </p>
        )}
      </div>
    </div>
  );
}
