import { auth } from "@clerk/nextjs/server";
import { getIdeasMarkdown } from "@/lib/data";
import { getCurationState } from "@/lib/curation";
import { parseIdeasMarkdown } from "@/lib/ideas-parser";
import { IdeasBoard } from "@/components/ideas-board";

export const dynamic = "force-dynamic";

export default async function IdeasPage() {
  const { userId } = await auth();
  if (!userId) return null; // proxy.ts already guarantees this; satisfies TS

  const markdown = getIdeasMarkdown();
  const parsed = parseIdeasMarkdown(markdown);
  const { ideas: initialCuration, favoriteIdeas } = await getCurationState(userId);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">
          Stage 2
        </p>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
          Generated startup ideas
        </h1>
        <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
          Generated by a Claude session reading the grounded trend context (no API
          key — see <code className="rounded bg-secondary px-1.5 py-0.5">data/idea_prompt.md</code>{" "}
          for the source prompt). Rate each idea — ratings are saved to your own
          account, separate from anyone else using this dashboard.
        </p>
      </div>

      {parsed.ideas.length > 0 ? (
        <IdeasBoard
          parsed={parsed}
          initialCuration={initialCuration}
          initialFavorites={favoriteIdeas}
        />
      ) : (
        <div className="rounded-[1.75rem] border border-border/80 bg-card p-6 shadow-sm sm:p-8">
          <p className="py-8 text-center text-sm text-muted-foreground">
            No ideas generated yet — run{" "}
            <code className="rounded bg-secondary px-1.5 py-0.5">
              build_idea_context.py
            </code>{" "}
            and have a Claude session write{" "}
            <code className="rounded bg-secondary px-1.5 py-0.5">data/ideas.md</code>.
          </p>
        </div>
      )}
    </div>
  );
}
